server:
  port: 9001
  
eureka:
  client:
    service-url:
       defaultZone: http://localhost:9000/eureka/
       
zuul:  routes:    user:                           #定义模块
      service-id: user-provider     #用户模块服务的名称
      path: /user/**                #url中包含user的请求，可以访问服务名为user-provider的微服务
    goods:
      service-id: goods-provider    #商品模块服务的名称
      path: /goods/**               #url中包含goods的请求，可以访问服务名为goods-provider的微服务
    orders:
      service-id: orders-provider   #订单模块服务的名称
      path: /orders/**              #url中包含orders的请求，可以访问服务名为orders-provider的微服务                                               